FROM fishjerky/centos-base:7

#############################
# Go
ENV GO_VERSION 1.16.5
RUN wget https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz && rm -rf /usr/local/go && tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz
RUN mkdir -p /go/bin /go/pkg /go/src
ENV GOPATH /go
RUN echo "export PATH=\"/usr/local/go/bin:/go/bin:$PATH\"" >> /root/.bashrc
ENV PATH="usr/local/go/bin:/go/bin:${PATH}"
RUN go env -w GO111MODULE=auto


######
RUN rpm -ivh https://download.oracle.com/otn_software/linux/instantclient/211000/oracle-instantclient-basic-21.1.0.0.0-1.x86_64.rpm http://mirror.centos.org/centos/7/os/x86_64/Packages/libaio-0.3.109-13.el7.x86_64.rpm
#

#############################
# Cloud9 IDE
EXPOSE 8080

#############################
# Web apps may use these ports
EXPOSE 8081
EXPOSE 8082

# add in some nice Cloud9 default settings
COPY user.settings /root/.c9/
COPY .c9 /go/.c9

# install cloud9 last to make updates smaller
RUN git clone git://github.com/c9/core.git c9sdk
RUN cd c9sdk; ./scripts/install-sdk.sh; ln -s /c9sdk/bin/c9 /usr/bin/c9; ln -s /root/.c9/node/bin/node /usr/bin/node

# start cloud9 with no authentication by default
# if authentication is desired, set the value of -a, i.e. -a user:pass at docker run
ENTRYPOINT ["/root/.c9/node/bin/node", "c9sdk/server.js", "-w", "/go", "--listen", "0.0.0.0", "-p", "8080"]i
CMD ["-a", ":"]
